[package]
distribution = "2201.10.0"
org = "wso2"
name = "hubspot.crm.import"
version = "1.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["hubspot","crm", "imports"]
repository = "https://github.com/ballerina-platform/module-ballerinax-hubspot.crm.import"

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true
